server:
  port: 8080
spring:
  profiles:
    active: dev
---
server:
  port: 8081
spring:
  profiles: dev
---
server:
  port: 8082
spring:
  profiles: prod


#person:
#    lastName: zhangsan
#    age: 18
#    boss: false
#    birth: 2017/12/12
#    maps: {k1: v1,k2: 12}
#    lists:
#     - lisi
#     - zhaowu
#     - koliu
#    dog:
#      name: xiaohua
#      age: 2